### ISSUE TITLE
Enhancement: 챗봇 다른 페이지에 붙일 수 있게 변경

### ISSUE THREAD

**Issue by JEESW** [high-five-ormi/Algoy-Web#100]
## TODO
  - [x] 챗봇 UI를 햄버거 메뉴 스타일로 변경
  - [x] 챗봇 코드에 Thymeleaf를 적용하여 프래그먼트로 변환
  - [x] 세션 스토리지를 사용하여 대화 내용 유지
  - [x] 새로고침이나 페이지 변경 후 스크롤 아래부터 보여지게 하기

## 설명
햄버거 메뉴란 디스코드 음성 채팅 안의 채팅 버튼 처럼 누르면 화면이 보이고 한 번 더 누르면 안보이게 하는 기능입니다. 이 기능을 이용해 다양한 페이지에서도 프래그먼트로 붙여 사용할 수 있게 하는 것이 목표입니다. 또 세션 스토리지를 이용하여 채팅 기록이 사라지지 않게 하여 사용자 편의성을 증가시키는 목표도 가지고 있습니다.
