### ISSUE TITLE
Feat: solvedAC에서 호출한 100문제 기반으로 allen에게 문제 추천받기

### ISSUE THREAD

**Issue by ARaZoAnna** [high-five-ormi/Algoy-Web#103]
## TODO
  - [x] 8081(Web)에서는 user정보만 넘겨주고 답변을 받아서 화면에 랜더링 하는 것으로 로직을 간편화 하기
  - [x] 8082(AI)에서 user 정보 기반으로 solvedAC에서 100문제 받아오기
  - [x] 앨런AI에게 문제 기반한 질문을 요청하고 답변을 받기
  - [x] 해당 답변은 8081(Web)으로 리턴하기
  - [x] 로컬에서 테스트

## 설명
기존 개발: 
8081(Web)에서 solvedAC API 호출 로직을 작성했는데 이후 8082에 데이터를 전송할때 리스트에서 Json으로 변경하고 
8082(AI)에서 Json을 다시 String으로 변경해야하는 하나의 데이터로 반복적인 변환을 해야하는 것이 비효율적입니다.
변경 후 개발:
8081(Web)에서 파라미터만 8082(AI)에 전달하고 solvedAC 연동 및 allen API 호출을 8082(AI)에서 로직 개발했습니다.
Json->String으로만 변경하면 되어 더욱 효율적이라 판단했습니다.
