### ISSUE TITLE
Feature: 회원 탈퇴

### ISSUE THREAD

**Issue by jooyom** [high-five-ormi/Algoy-Web#105]
## TODO
  - [x] 회원 탈퇴 여부 html + 기능 연동
  - [x] 탈퇴 회원 로그인 시 html 
  - [x] 탈퇴 회원 복구 html + 기능 연동
  - [x] 탈퇴 회원 정보 삭제

## 설명
- 마이페이지 모달 내 회원 탈퇴 기능 업데이트
- 회원 탈퇴 시 alt를 통해 탈퇴 여부를 물어봅니다.
- 탈퇴 신청 된 아이디로 로그인 시 계정을 복구할 건지 물어보는 페이지로 이동합니다.
- 복구를 하게되면 로그인에 성공하고 홈으로 이동합니다.
- 복구를 하지 않을 경우 로그아웃되며 홈으로 이동합니다.
- 로컬에서는 잘 작동합니다!
