### ISSUE TITLE
Design: 페이지에 챗봇 붙이기

### ISSUE THREAD

**Issue by JEESW** [high-five-ormi/Algoy-Web#110]
## TODO
  - [x] 홈 화면에 챗봇 프래그먼트 붙이기
  - [x] 오답노트 화면에 챗봇 프래그먼트 붙이기
  - [x] 플래너 화면에 챗봇 프래그먼트 붙이기
  - [x] 스터디 모집 화면에 챗봇 프래그먼트 붙이기

## 설명
화면마다 챗봇 버튼 붙이기
