### ISSUE TITLE
Feature: 홈 화면 플래너 연동

### ISSUE THREAD

**Issue by jooyom** [high-five-ormi/Algoy-Web#114]
## TODO
  - [ ] fullcalendar에 플래너 연동하기
  - [ ] chart에 플래너 연동하기
  - [ ] chart는 한달 단위로 시작 전/ 진행 중/ 완료 갯수 취합하여 보여주기
  - [ ] fullcalendar와 chart연동하여 월별로 보이도록 연동하기
