### ISSUE TITLE
Feature: 회원 권한 관리

### ISSUE THREAD

**Issue by duys2** [high-five-ormi/Algoy-Web#121]
## TODO
  - [x] 관리자 페이지 생성
  - [x] 관리자 페이지: 유저의 정보 표기
  - [x] 관리자 권한: 해당 유저 정지 처리, 관리자 임명

## 설명
유저의 권한을 컨트롤 합니다.
