### ISSUE TITLE
Feat: 앨런의 답변(마크다운) 정제하기

### ISSUE THREAD

**Issue by ARaZoAnna** [high-five-ormi/Algoy-Web#123]
## TODO
  - [x] 앨런에게 문제추천을 JSON 형태로 답변 받기
  - [x] 마크다운 문법 제거하기
  - [x] JSON을 텍스트 형태로 변환하여 화면에 띄우기

## 설명
앨런에게 답변 받을때 마크다운으로 답변을 받습니다. 
이를 처리하기 위해 마크다운 분법을 제거하고 JSON 형태를 text로 변환하여 화면에 출력합니다
