### ISSUE TITLE
Enhancement: SolvedAC username을 회원 정보에 저장하기

### ISSUE THREAD

**Issue by ARaZoAnna** [high-five-ormi/Algoy-Web#127]
## TODO
  - [x] 회원가입란에 solvedAC username을 입력하는 데이터 값 생성(선택사항)
  - [x] 회원정보 수정란에 solvedAC username을 입력하는 란 생성
  - [x] username이 null이면 alan 연동하지 않는다.
  - [x] username이 not null이면 alan을 연동하여 문제 추천을 받는다

## 설명
앨런 추천을 받기위한 SolvedAC username을 회원가입시 또는 회원정보 수정시 입력받는(선택사항) 기능을 구현합니다.
