### ISSUE TITLE
Feature: 회원가입시 SolvedAC username을 입력(선택)받고 유효성 검사하기

### ISSUE THREAD

**Issue by ARaZoAnna** [high-five-ormi/Algoy-Web#149]
## TODO
  - [x] 회원가입시 solvedAC username을 입력받는 필드 생성
  - [x] api를 통해 유효성 검사
  - [x] username이 유효하면 db에 저장
  - [x] 유효하지 않다면 db에 저장하지 않음
  - [x] 유효성 검사를 하지 않은 경우 저장하지 않음
  - [x] 로컬 환경 테스트
  - [x] 배포 환경 테스트

## 설명
회원 가입 또는 회원 정보 수정을 통해 solvedAC username을 저장할 수 있다. 
이를 기반으로 AI 추천을 받는다.
