### ISSUE TITLE
Feature: 유저 정지 개선

### ISSUE THREAD

**Issue by duys2** [high-five-ormi/Algoy-Web#155]
## TODO
  - [x] 유저 정지 사유 추가 
  - [x] 유저 정지 방식 변경
  - [x] banCount 타입 변경
  - [x] 유저 권한 제어는 UserPermissionService.java로 따로 분리

## 설명
유저 정지 방식 변경
- 버튼 클릭 → 버튼 클릭 시 모달창 생성 → 정지 사유 입력 후 확인 → 유저 정지
- banReason 추가 후 관련 코드 작업
- banCount 타입 변경: Integer → int
