### ISSUE TITLE
Refactor: 채팅 기능과 챗봇 기능 같은 페이지에서 쓸 수 있도록 조정

### ISSUE THREAD

**Issue by JEESW** [high-five-ormi/Algoy-Web#161]
## TODO
  - [x] 채팅 접두사 chat-frag로 지정
  - [x] 챗봇 접두사 bot-frag로 지정
  - [x] 위치 조정 및 충돌 체크

## 설명
채팅 기능과 챗봇 기능이 겹치는 구간이 있어 충돌이 나지 않게 조정이 필요합니다.
