### ISSUE TITLE
Test: 채팅 기능 단위 테스트 코드 작성

### ISSUE THREAD

**Issue by JEESW** [high-five-ormi/Algoy-Web#164]
## TODO
  - [x] Controller 단위 테스트 작성
  - [x] Service 단위 테스트 작성
  - [x] Repository 단위 테스트 작성

## 설명
채팅 기능 단위 테스트를 작성합니다.
