### ISSUE TITLE
Deploy: 계속된 서버 다운으로 배포 재실행

### ISSUE THREAD

**Issue by ARaZoAnna** [high-five-ormi/Algoy-Web#196]
## TODO
  - [x] 서버에서 배포할때 디버깅을 통해 다운되는 원인 찾기
  - [x] 출력을 출여보기
  - [x] 새로 실행된 서버에서 배포하기
  - [x] EC2 t3 환경설정하고 이전 준비하기

## 설명
하루 한 번 이상 서버가 다운되는 이슈가 발생
SCP 실행시 1시간 30분이나 네트워크 통신 시간이 길어짐
이후 서버 다운되고 SSH로 서버 접속이 불가능
원인을 파악하고 메모리 문제라면 t3로 서버 변경 예정
