### ISSUE TITLE
Enhancement: 채팅 기능 보완

### ISSUE THREAD

**Issue by JEESW** [high-five-ormi/Algoy-Web#216]
## TODO
  - [x] 햄버거 메뉴 vw, vh로 단위 변경
  - [x] 시스템 알림을 초대 되었을 때와 채팅방 나갈때로 변경
  - [x] 시스템 알림도 DB에 메시지로 저장

## 설명
햄버거 메뉴가 화면 크기에 따라 안 보이는 경우가 있어 이를 방지하기 위해 vw, vh 단위를 사용합니다.
