### ISSUE TITLE
refactor: 로그인+회원가입

### ISSUE THREAD

**Issue by jooyom** [high-five-ormi/Algoy-Web#38]
## TODO
  - [ ] 로그인과 회원가입 합치기
  - [ ] HTML 주소 연결하기
  - [ ] Home화면 헤더 구성
