### ISSUE TITLE
깃허브 액션으로 CI/CD 구축하기 

### ISSUE THREAD

**Issue by ARaZoAnna** [high-five-ormi/Algoy-Web#4]
## TODO
  - [x] 배포 yml 파일 작성
  - [x] 깃허브 액션으로 CI/CD AWS EC2에 배포하기
  - [x] yml 파일 수정해서 Docker images 파일로 배포하기

## 설명
개발의 생산성 증대를 위해 CI/CD 구축 후 개발을 한다. 
AWS EC2, GitHub Actions, RDS, Docker
