### ISSUE TITLE
Bug: oauth2.0 오류

### ISSUE THREAD

**Issue by duys2** [high-five-ormi/Algoy-Web#44]
## TODO
  - [x] application.yml에 설정값 환경 변수로 추가
  - [x] gradle.yml 환경 변수
  - [x] 배포 오류 해결되는지 확인

## 설명
oauth2.0 관련 에러
