### ISSUE TITLE
Refactor: 코드 리펙토링

### ISSUE THREAD

**Issue by duys2** [high-five-ormi/Algoy-Web#53]
## TODO
  - [x] 비밀번호 확인을 UserController가 아닌 js로 처리
  - [x] 메서드에 JavaDoc 주석 추가
  - [x] 코드 포매팅
  - [x] 구글 로그인 관련 파일 패키지 이동•정리

## 설명
코드 리펙토링
- 주작업: 비밀번호 확인 처리를 signup.js로 처리하기
