### ISSUE TITLE
Design: 홈 화면 edit

### ISSUE THREAD

**Issue by jooyom** [high-five-ormi/Algoy-Web#57]
## TODO
  - [ ] 홈 화면 캘린더 추가
  - [ ] 홈 화면 요약 추가
  - [ ] 홈 화면 - 모달추가 (추후에 모듈화 고려중)
  - [ ] 로그인 화면 - 구글 이미지 추가
