### ISSUE TITLE
Design: 회원정보 수정

### ISSUE THREAD

**Issue by jooyom** [high-five-ormi/Algoy-Web#62]
## TODO
  - [ ] 회원정보 수정 페이지 구현
  - [ ] 기존 기능 코드로 수정까지 가능하도록 기능 연결
  - [ ] 회원 삭제 구현 
  - [ ] 홈, 로그인 화면 CSS 수정

## 설명
ajax 통신
