### ISSUE TITLE
Feat : SolvedAC API를 통해 앨런에게 문제 추천받기

### ISSUE THREAD

**Issue by ARaZoAnna** [high-five-ormi/Algoy-Web#70]
## TODO
  - [x] SolvedAC API 호출하기
  - [x] 데이터를 Algoy-Ai 애플리케이션(8082)에 보내기
  - [x] 앨런에게 받은 답변을 web에서 띄우기

## 설명
FE를 WEB(8081) 쪽에 구현한다. 백준 ID를 입력하면 solvedAC의 api를 통해 해당 아이디의 정보를 기반으로 문제를 추천받는다.(8082)
RestFulAPI를 통해 두 서버간의 통신을 한다.
