### ISSUE TITLE
Feat: Web에서 solvedAC API 연동하여 사용자가 푼 상위 100문제 가져오기

### ISSUE THREAD

**Issue by ARaZoAnna** [high-five-ormi/Algoy-Web#99]
## TODO
  - [x] HTTP를 통해 solvedAC에서 사용자가 푼 문제 중 상위 100문제를 호출하기
  - [x] Json을 파싱하여 List에 100문제의 제목을 넣어 반환하기
  - [x] 기능 수행 확인하기

## 설명
유저가 solvedAC 닉네임을 입력하면 닉네임을 기반하여 solvedAC API를 통해 상위 100문제를 추출한다. 
유저가 푼 100 문제를 List에 담아서 앨런 AI 애플리케이션에 데이터를 던져준다.
